# Generated by Django 4.2.2 on 2023-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=40)),
                ('correo_contacto', models.CharField(max_length=50)),
                ('telefono_contacto', models.IntegerField()),
                ('ciudad_contacto', models.CharField(max_length=40)),
                ('mensaje_contacto', models.CharField(max_length=110)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('correo_usuario', models.CharField(max_length=50)),
                ('contrasena_usuario', models.CharField(max_length=30)),
            ],
        ),
    ]
