# Generated by Django 4.2.2 on 2023-06-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botilleria_covid_paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='pendiente', max_length=20),
        ),
    ]
