# Generated by Django 4.2.2 on 2023-06-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botilleria_covid_paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_django',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=40)),
                ('contrasena_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botilleria_covid_paginas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botilleria_covid_paginas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion_imagen', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_producto', models.CharField(max_length=30)),
                ('descripcion_producto', models.CharField(max_length=50)),
                ('precio_producto', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='', verbose_name='Foto')),
                ('informacion_adicional', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_botilleria.compras')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_botilleria.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_botilleria.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_botilleria.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_botilleria.productos')),
            ],
        ),
    ]
