# Generated by Django 4.2.2 on 2023-06-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_botilleria', '0002_productos_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Almacen',
        ),
    ]
